cookbook/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^user/', include('userauth.urls')),
    
    url(r'^news/', include('news.urls')),
    
    url(r'^', include('recipes.urls')),
 
	
)

news/urls.py
from django.conf.urls import patterns, include, url

from news.feeds import ArticleFeed
from news.views import ArticleDetailView, ArticleListView

urlpatterns = patterns('',
	url(r'^feed/rss/$', ArticleFeed(), name='news_article_feed'),
	url(r'^(?P<pk>\d+)/$', ArticleDetailView.as_view(), name='news_article_detail'),
	url(r'^$', ArticleListView.as_view(), name='news_article_list'),
)

recipes/urls.py
from django.conf.urls.defaults import patterns, include, url

from recipes.views import RecipeDetailView, RecipeListView, RecipePDFView

from recipes.api import RecipeResource
recipe_resource = RecipeResource()


urlpatterns = patterns('recipes.views',
    url(r'^add/$', 'add', name='recipes_recipe_add'),
    url(r'^edit/(?P<recipe_id>\d+)/$', 'edit', name='recipes_recipe_edit'),
)

urlpatterns += patterns('',
	url(r'^recipes/(?P<slug>[-\w]+)/$', RecipeDetailView.as_view(),
		name='recipes_recipe_detail'),
	url(r'^recipes/(?P<slug>[-\w]+)/pdf/$', RecipePDFView.as_view(),
		name='recipes_recipe_detail_pdf'),
	url(r'^$', RecipeListView.as_view(), name='recipes_recipe_index'),
)

urlpatterns += patterns('',
	url(r'^api/', include(recipe_resource.urls)),
)

recipes/models.py
# encoding: utf-8
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now


class Category(models.Model):
	"""Category model."""
	name = models.CharField(u'Name', max_length=100)
	slug = models.SlugField(unique=True)
	description = models.TextField(u'Description', blank=True)

	class Meta:
		verbose_name = u'Category'
		verbose_name_plural = u'Categories'
		
	def __unicode__(self):
		return self.name

class ActiveRecipeManager(models.Manager):
	def get_query_set(self):
		return super(ActiveRecipeManager, self).get_query_set().filter(is_active=True)

class Recipe(models.Model):
	""" Recipe model. """
	is_active = models.BooleanField(u'Active')
	
	objects = models.Manager()
	active = ActiveRecipeManager()
	
	def get_related_recipes(self):
		categories = self.category.all()
		related_recipes = Recipe.active.all().filter(
			difficulty_exact=self.difficulty, category_in=categories)
		return related_recipes.exclude(pk=self.id).distinct()
	
	DIFFICULTY_EASY = 1
	DIFFICULTY_MEDIUM = 2
	DIFFICULTY_HARD = 3
	DIFFICULTIES = (
		(DIFFICULTY_EASY, u'easy'),
		(DIFFICULTY_MEDIUM, u'normal'),
		(DIFFICULTY_HARD, u'hard'),
	)
	title = models.CharField(u'Title', max_length=255)
	slug = models.SlugField(unique=True)
	ingredients = models.TextField(u'Ingredients',
		help_text = u'One ingredient per line')
	preparation = models.TextField(u'Preparation')
	time_for_preparation = models.IntegerField(u'Preparation Time',
		help_text = u'Specify time in minutes', blank=True, null=True)
	number_of_portions = models.PositiveIntegerField(u'Number of Portions')
	difficulty = models.SmallIntegerField(u'Difficulty',
		choices=DIFFICULTIES, default=DIFFICULTY_MEDIUM)
	category = models.ManyToManyField(Category, verbose_name=u'Categories')
	author = models.ForeignKey(User, verbose_name=u'Authors')
	date_created = models.DateTimeField(editable=False)
	date_updated = models.DateTimeField(editable=False)
	
	class Meta:
		verbose_name = u'Recipe'
		verbose_name_plural = u'Recipes'
		ordering = ['-date_created']
		
	def __unicode__(self):
		return self.title

	def save(self, *args, **kwargs):
		if not self.id:
			self.date_created = now()
		self.date_updated = now()
		super(Recipe, self).save(*args, **kwargs)
		
	@models.permalink
	def get_absolute_url(self):
		return ('recipes_recipe_detail', (), { 'slug': self.slug })

recipes/forms.py
from django.forms import ModelForm
from django.template.defaultfilters import slugify

from recipes.models import Recipe

class RecipeForm(ModelForm):
	class Meta:
		model = Recipe
		exclude = ('slug', 'author', 'date_created', 'date_updated')

	def __init__(self, **kwargs):
		self.__user = kwargs.pop('user', None)
		super(RecipeForm, self).__init__(**kwargs)
		
	def save(self, commit=True):
		if self.instance.pk is None:
			if self.__user is None:
				raise TypeError("You didn't give an user argument to the constructor.")
			self.instance.slug = slugify(self.instance.title)
			self.instance.author = self.__user
		return super(RecipeForm, self).save(commit)

recipes/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseForbidden, HttpResponseRedirect
from django.contrib.auth.decorators import login_required

from django.views.generic import DetailView, ListView

from cookbook.views import PDFView

# Data models and forms
from recipes.models import Recipe
from recipes.forms import RecipeForm

# Logging
import logging
logger = logging.getLogger(__name__)

class RecipePDFView(PDFView):
	model = Recipe
	template_name = 'recipes/detail_pdf.html'
		

class RecipeListView(ListView):
	template_name = 'recipes/index.html'
	
	def get_queryset(self):
		recipes = Recipe.active.all()
		logger.debug('Number of Recipes: %d' % recipes.count())
		return recipes
		
class RecipeDetailView(DetailView):
	queryset = Recipe.active.all()
	template_name = 'recipes/detail.html'


def detail(request, slug):
	recipe = get_object_or_404(Recipe, slug=slug)
	return render(request, 'recipes/detail.html', 
		{'object': recipe})
		
@login_required
def add(request):
	if request.method == 'POST':
		form = RecipeForm(user=request.user, data=request.POST)
		if form.is_valid():
			recipe=form.save()
			return HttpResponseRedirect(recipe.get_absolute_url())
	else:
		form = RecipeForm()
	return render(request, 'recipes/form.html',
		{'form': form, 'add': True})

@login_required
def edit(request, recipe_id):
	recipe = get_object_or_404(Recipe, pk=recipe_id)
	if recipe.author != request.user and not request.user.is_staff:
		return HttpResponseForbidden()
	if request.method == 'POST':
		form = RecipeForm(instance=recipe, data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(recipe.get_absolute_url())
	else:
		form = RecipeForm(instance=recipe)
	return render(request, 'recipes/form.html',
		{'form': form, 'add': False, 'object': recipe})

recipes/templates/recipes/detail.html
{% extends "base.html" %}

{% block title %}{{ block.super }} - {{ object.title }}{% endblock %}

{% block content %}
<h2>{{ object.title }}</h2>
<a href="{% url recipes_recipe_index %}">Return to Overview</a>

<a href="{% url recipes_recipe_edit object.pk %}">Edit Recipe</a>

<a href='{% url recipes_recipe_detail_pdf object.slug %}'>View Recipe as PDF</a>
<p> {{ object.number_of_portions }} 
	Portion{{ object.number_of_portions|pluralize:"en" }}.</p>
<h3>Ingredients</h3>
{{ object.ingredients|linebreaks }}
<h3>Preparation</h3>
{{ object.preparation|linebreaks }}
<p>Preparation time: {{ object.time_for_preparation }} minutes</p>

<p>Difficulty: {{ object.get_difficulty_display }}</p>
<p>Author: {{ object.author }}</p>

<h4>Category{{ object.category.count|pluralize:"ies" }}</h4>
<ul>
	{% for category in object.category.all %}
		<li>{{ category.name }}</li>
	{% endfor %}
	
</ul>
{% endblock %}

recipes/templates/recipes/detail_pdf.html
{% extends 'base.html' %}

{% block title %}{{ block.super }} - {{ object.title }}{% endblock %}

{% block toggle_login %}{% endblock %}

{% block content %}
{% load recipes %}
<h2>{{ object.title }}</h2>
<p>Difficulty: {{ object.get_difficulty_display }}</p>
<p>Portions: {{ object.number_of_portions }}
	Portion{{ object.number_of_portions|pluralize:"en" }}.</p>
<h3>Ingredients</h3>
{{ object.ingredients|linebreaks }}
<h3>Preparation</h3>
{{ object.preparation|linebreaks }}
<p>Preparation time: {{ object.time_of_preparation }} Minutes</p>
<p> Author: {{ object.author }}</p>
<h4>Category{{ object.category.count|pluralize:"n" }}</h4>
<ul>
	{% for category in object.category.all %}
		<li>{{ category.name }}</li>
	{% endfor %}
</ul>
{% get_related_recipes object 5 as related_recipes %}
{% if related_recipes %}
<h4>Related Recipes</h4>
<ul>
{% for recipe in related_recipes %}
	<li>{{ recipe.title }}</li>
{% endfor %}
</ul>
{% endif %}
{% endblock %}

recipes/templates/recipes/form.html
{% extends 'base.html' %}

{% block title %}
{{ block.super}} - Recipe {% if add %}Add
	{% else %}"{{ object.title }}" edit{% endif %}
{% endblock %}

{% block content %}
{% if add %}
<h2>Add Recipe</h2>
{% url recipes_recipe_add as action_url %}
{% else %}
<h2>Recipe "{{ object.title }}" edit</h2>
{% url recipes_recipe_edit object.pk as action_url %}
{% endif %}
<form action="{{ action_url }}" method="post"  accept-charset="utf-8">
	{{ form.as_p }}
	{% csrf_token %}
	<p><input type='submit' value='Save'</p>
</form>
<a href="{% url recipes_recipe_index %}">Back to List</a>
{% endblock %}

recipes/templates/recipes/index.html
{% extends 'base.html' %}
<div class='container_12'>
{% block title %}{{ block.super }} - All Recipes{% endblock %}

{% block content %}


<h2>All Recipes</h2>
<a href="{% url recipes_recipe_add %}">Add Recipe</a>
	

</div>

<div class='grid_10 suffix_1'>
<ul>
	{% for recipe in object_list %}
	<li><a href="{{ recipe.get_absolute_url }}">{{ recipe.title }}</a></li>
	{% endfor %}
</ul>
</div> <!-- End Recipe List Grid -->
</div>
</div>

</div> <!-- End Page Container -->
{% endblock %}